---
- name: makecache for repo (assume yes) (RHEL)
  command: yum -y makecache
  args:
    warn: no

- name: Add the xroad user
  user:
    name: xroad_ui_user
  when: database_admin_password != ""

- name: Create xroad directory
  file:
    path: /etc/xroad
    state: directory
    mode: '0751'
    owner: xroad_ui_user
    group:  xroad_ui_user
  when: database_admin_password != ""

- name: generate opmonitor_admin_password
  set_fact: opmonitor_admin_password="{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits length=32') }}"
  when: (database_admin_password != "") and (opmonitor_admin_password == "")

- name: xroad.properties template
  template:
    src: "xroad.properties"
    dest: "/etc/xroad.properties"
    owner: "root"
    group: "root"
    mode: 0600
  when: database_admin_password != ""

- name: generate serverconf_password
  set_fact: serverconf_password="{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits length=32') }}"
  when: (database_admin_password != "") and (serverconf_password == "")

- name: generate opmonitor_password
  set_fact: opmonitor_password="{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits length=32') }}"
  when: (database_admin_password != "") and (opmonitor_password == "")

- name: generate messagelog_password
  set_fact: messagelog_password="{{ lookup('password', '/dev/null chars=ascii_letters,digits,hexdigits length=32') }}"
  when: (database_admin_password != "") and (messagelog_password == "")
  
- name: db.properties template
  template:
    src: "db.properties"
    dest: "/etc/xroad/db.properties"
    owner: "xroad"
    group: "xroad"
    mode: 0751
  when: database_admin_password != ""

# verify presence of xroad packages and dependencies
- name: install xroad packages and dependencies from set up repository (RHEL)
  yum:
    name: "{{ vars['xroad_varpkg_' + variant] }}"
    state: present

# update all xroad packages to their latest version in the set up repo
- name: update xroad security server to latest (RHEL)
  yum:
    name: "*"
    state: latest
    disablerepo: "*"
    enablerepo: xroad-{{package_source}}-repository

- name: add xroad admin user
  command: "xroad-add-admin-user {{ xroad_ui_user }}"

- name: start xroad-proxy (RHEL)
  service:
    name: xroad-proxy
    state: started
