xroad_ca_dn_country: "FI"
xroad_ca_o: "X-Road Test"
xroad_ca_ou: "X-Road Test CA OU"
xroad_ca_cn: "X-Road Test CA CN"
xroad_ca_ocsp_o: "X-Road Test"
xroad_ca_ocsp_ou: "X-Road Test OCSP OU"
xroad_ca_ocsp_cn: "X-Road Test OCSP CN"
xroad_ca_tsa_o: "X-Road Test"
xroad_ca_tsa_ou: "X-Road Test TSA OU"
xroad_ca_tsa_cn: "X-Road Test TSA CN"
