---
# This playbook installs an X-Road environment to the defined host inventory from a remote package repository

- hosts: lxd-servers
  roles:
    - init-lxd
  tags:
    - init

- hosts: ss-servers
  any_errors_fatal: true
  tasks:
    - name: RHEL-support check
      fail:
        msg: "Variant '{{ variant }}' does not support RHEL-servers"
      when:
        - (variant is defined and variant == "ee")
        - ansible_os_family == "RedHat"

- hosts: cs-servers
  become: yes
  become_user: root
  roles:
    - xroad-cs
  tags:
    - cs
  vars_files:
    - vars_files/remote_repo.yml

- hosts: cp-servers
  become: yes
  become_user: root
  roles:
    - xroad-cp
  tags:
    - cp
  vars_files:
    - vars_files/remote_repo.yml

- hosts: ss-servers
  become: yes
  become_user: root
  roles:
    - xroad-ss
  tags:
    - ss
  vars_files:
    - vars_files/remote_repo.yml
    - vars_files/ss_database.yml

- hosts: ca-servers
  become: yes
  become_user: root
  pre_tasks:
    - raw: apt install openssl
  roles:
    - role: xroad-ca
      tags: [ 'ca' ]
