---
- name: Install epel repository (RHEL)
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"

- name: Install required packages (RHEL)
  become: yes
  yum:
    name: "{{ items }}"
    state: present
  vars:
    items:
      - curl
      - createrepo
      - cronie
      - tar

- name: Create / update local package repository (RHEL)
  become: yes
  command: createrepo /xroad/local
  when: package_source == "local"
  args:
    chdir: /xroad/local
  tags: centos-repo

- name: Setup the correct repository for X-Road installation (RHEL)
  yum_repository:
    name: xroad-{{package_source}}-repository
    description: Repository for installing X-Road packages
    baseurl: "{{ rhel_repo_baseurl }}"
    gpgcheck: "{{ rhel_repo_gpgcheck }}"
    gpgkey: "{{ rhel_repo_gpgkey }}"
    repo_gpgcheck: "{{ rhel_repo_gpgcheck }}"
    state: present
    enabled: yes
